apiVersion: v1
kind: Service
metadata:
  name: iot-frontend
  namespace: iot-platform
  labels:
    app: iot-frontend
    tier: frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: iot-frontend
